spring.application.name=review-site
#spring.main.web-application-type=none

spring.ai.mcp.server.name=book-reviews-mcp
spring.ai.mcp.server.version=0.0.1

# Server type (SYNC/ASYNC)
#spring.ai.mcp.server.type=SYNC

# Transport configuration
spring.ai.mcp.server.stdio=false
#spring.ai.mcp.server.sse-message-endpoint=/mcp/message

# Change notifications
#spring.ai.mcp.server.resource-change-notification=true
#spring.ai.mcp.server.tool-change-notification=true
#spring.ai.mcp.server.prompt-change-notification=true

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
spring.main.banner-mode=console
#logging.pattern.console=target/mcp.review.site.log

logging.level.org.springframework.ai=DEBUG
server.address=0.0.0.0
server.port=3001

#H2 DB Settings
spring.jpa.database-platform=H2
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

#Resilience Settings

#Bulkhead
resilience4j.bulkhead.metrics.enabled=true
resilience4j.bulkhead.instances.reviewBulkhead.maxConcurrentCalls=5
resilience4j.bulkhead.instances.reviewBulkhead.maxWaitDuration=1000

#Circuit Breaker
# If the service fails more than 50% of the time in a window of 5 calls, the circuit opens.
# After 10 seconds, it enters half-open state and allows a few calls.
# If those calls succeed, it resets to closed; otherwise, it goes back to open.
resilience4j.circuitbreaker.instances.reviewCircuit.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.reviewCircuit.slidingWindowSize=5
resilience4j.circuitbreaker.instances.reviewCircuit.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.reviewCircuit.failureRateThreshold=50
resilience4j.circuitbreaker.instances.reviewCircuit.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.reviewCircuit.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.reviewCircuit.slidingWindowType=COUNT_BASED
